template:
  # 项目存放文件夹名字
  rootPath: base-svc-financing-scheme
  # 包路径
  packagePath: cn/net/cdsz/svc/financingscheme
  #服务路径
  svcPath: ${template.rootPath}
  # api路径
  apiPath: ${template.rootPath}-api
  #过滤表前缀
  tablePrefix: tb_
  apiFullPackagePath: ${template.rootPath}/${template.apiPath}/src/main/java/${template.packagePath}
  svcFullPackagePath: ${template.rootPath}/${template.svcPath}/src/main/java/${template.packagePath}
  resFullPackagePath: ${template.rootPath}/${template.svcPath}/src/main/resources
  # 共通模板变量
  ctx:
    #包名
    package: cn.net.cdsz.svc.financingscheme
    author: chengfaying
    appName: ${template.rootPath}

  #生成服务代码
  #按模块生成空文件夹（多个模块）${moduleName}根据传入的模块名替换
  app:
    #空文件夹（模块《moduleName》上下文文件夹及一些特殊的单文件加）
    emptyFiles:
      - ${template.svcFullPackagePath}/application/${moduleName}/.gitkeep
      - ${template.svcFullPackagePath}/domain/${moduleName}/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/persistent/${moduleName}/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/repository/${moduleName}/.gitkeep
      - ${template.svcFullPackagePath}/interfaces/rest/${moduleName}/.gitkeep
      - ${template.resFullPackagePath}/mapper/${moduleName}/.gitkeep
      - ${template.apiFullPackagePath}/api/${moduleName}/.gitkeep
      - ${template.apiFullPackagePath}/dto/${moduleName}/.gitkeep
      - ${template.apiFullPackagePath}/vo/${moduleName}/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/config/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/constants/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/external/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/mq/.gitkeep
      - ${template.svcFullPackagePath}/infrastructure/redis/.gitkeep
    templateFiles:
      # 模板路径（resource目录下）: 生成路径（项目）
      "[template/app/parent-pom.xml.vm]": ${template.rootPath}/pom.xml
      "[template/app/svc-pom.xml.vm]": ${template.rootPath}/${template.svcPath}/pom.xml
      "[template/app/api-pom.xml.vm]": ${template.rootPath}/${template.apiPath}/pom.xml
      "[template/app/Application.java.vm]": ${template.svcFullPackagePath}/Application.java
      # 文件夹支持 ：读取文件夹下的所有模板，渲染后放到配置的文件夹下（保持相对路径、并去掉模板后缀.vm）
      "[template/app/apiconstants]": ${template.apiFullPackagePath}/constants
      "[template/app/svcinfrastructure]": ${template.svcFullPackagePath}/infrastructure
      "[template/app/resources]": ${template.resFullPackagePath}
  #逆向根据表生成业务代码
  tables:
    emptyFiles:
    templateFiles:
      "[template/tables/Api.java.vm]": ${template.apiFullPackagePath}/api/${moduleName}/I${className}Api.java@keyApi
      "[template/tables/ApiDTO.java.vm]": ${template.apiFullPackagePath}/dto/${moduleName}/${className}DTO.java@keyDTO
      "[template/tables/ApiVO.java.vm]": ${template.apiFullPackagePath}/vo/${moduleName}/${className}VO.java@keyVO
      "[template/tables/Application.java.vm]": ${template.svcFullPackagePath}/application/${moduleName}/${className}Application.java@keyApplication
      "[template/tables/AppRepository.java.vm]": ${template.svcFullPackagePath}/application/${moduleName}/repository/I${className}AppRepository.java@keyAppRepository
      "[template/tables/Controller.java.vm]": ${template.svcFullPackagePath}/interfaces/rest/${moduleName}/${className}Controller.java@keyController
      "[template/tables/DomainEntity.java.vm]": ${template.svcFullPackagePath}/domain/${moduleName}/entity/${className}DO.java@keyDO
      "[template/tables/DomainRepository.java.vm]": ${template.svcFullPackagePath}/domain/${moduleName}/repository/I${className}DomainRepository.java@keyDomainRepository
      "[template/tables/DomainService.java.vm]": ${template.svcFullPackagePath}/domain/${moduleName}/service/${className}DomainService.java@keyDomainService
      "[template/tables/InfrastructureAppRepository.java.vm]": ${template.svcFullPackagePath}/infrastructure/repository/${moduleName}/apprepo/${className}AppRepository.java@keyInsAppRepository
      "[template/tables/InfrastructureDomainRepository.java.vm]": ${template.svcFullPackagePath}/infrastructure/repository/${moduleName}/domainrepo/${className}DomainRepository.java@keyInsDomainRepository
      "[template/tables/PersistentMapper.java.vm]": ${template.svcFullPackagePath}/infrastructure/persistent/${moduleName}/mapper/${className}Mapper.java@keyMapper
      "[template/tables/PersistentPO.java.vm]": ${template.svcFullPackagePath}/infrastructure/persistent/${moduleName}/po/${className}PO.java@keyPO
      "[template/tables/PersistentPoService.java.vm]": ${template.svcFullPackagePath}/infrastructure/persistent/${moduleName}/${className}PoService.java@keyPoService

  attrType:
    tinyint: Integer
    smallint: Integer
    mediumint: Integer
    int: Integer
    integer: Integer
    bigint: Long
    float: Float
    double: Double
    decimal: BigDecimal
    bit: Boolean
    char: String
    varchar: String
    tinytext: String
    text: String
    mediumtext: String
    longtext: String
    date: Date
    datetime: Date
    timestamp: Date
    NUMBER: Integer
    INT: Integer
    INTEGER: Integer
    BINARY_INTEGER: Integer
    LONG: String
    FLOAT: Float
    BINARY_FLOAT: Float
    DOUBLE: Double
    BINARY_DOUBLE: Double
    DECIMAL: BigDecimal
    CHAR: String
    VARCHAR: String
    VARCHAR2: String
    NVARCHAR: String
    NVARCHAR2: String
    CLOB: String
    BLOB: String
    DATE: Date
    DATETIME: Date
    TIMESTAMP: Date
    TIMESTAMP(6): Date
    int8: Long
    int4: Integer
    int2: Integer
    numeric: BigDecimal
    json: String
